GET http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

################################################################

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
       "title" : "my title",
        "likes":5,
        "author": "archer",
        "url" : "www.archer.com",
        "user" : "5fda4026c994424d804e7af8"
}
################################################################

POST http://localhost:3003/api/blogs HTTP/1.
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZvbm55Ym95MyIsImlkIjoiNWZkYzhmYWZlNTQ1ZDZjNDA5Yjg3NzM1IiwiaWF0IjoxNjA4MjkwMjM5fQ.mTiEM9RxhSp21Jjj9UcDd7FhjEbwyhJ9n5bdLR8tr3Y

{
       "title" : "jest testing vonnyboy3",
        "likes":5,
        "author": "xxxx",
        "url" : "www.xxx.com",
        "user" :  "5fdc8fafe545d6c409b87735"
}

################################

DELETE http://localhost:3003/api/blogs/5fdc90a7e545d6c409b87737 HTTP/1.
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZvbm55Ym95MyIsImlkIjoiNWZkYzhmYWZlNTQ1ZDZjNDA5Yjg3NzM1IiwiaWF0IjoxNjA4MjkwMjM5fQ.mTiEM9RxhSp21Jjj9UcDd7FhjEbwyhJ9n5bdLR8tr3Y
